Algoritmo "Vetores Aula 1-B"
// Disciplina: Lógica de Programação e Algoritmos II
// Autor: Germano Rodrigues da Silva 
// Data atual  : 11/07/2024
Var
vetorNomes : vetor[1..5] de caracter
vetorIdade : vetor[1..5] de inteiro
i: inteiro
Inicio
Para i de 1 Ate 5 Faça
     Escreval("Informe o nome: ")
     Leia(vetorNomes[i])
Fimpara
Para i de 1 Ate 5 Faça
     Escreval("Informe a idade: ")
     Leia(vetorIdade[i])
Fimpara
Para i de 1 Ate 5 Faça
     Escreval("Nome: ", vetorNomes[i], " Idade: ", vetorIdade[i])
Fimpara


Fimalgoritmo