Algoritmo "Enquanto_2"
// Aula: Operadores e Exercícios
// Autor: Germano Rodrigues da Silva
// Data atual  : 09/07/2024
Var
   n, i:inteiro


Inicio
   Escreval("Informe um número de inicio: ")
   Leia(i)
   Escreval("Informe onde qual será o ultimo número")
   Leia(n)
   Enquanto i < n faça
      i <- i + 1
      Escreval(i)
      Se i = 50 entao
         Escreval("Oi meus amores! <3")
         interrompa
      fimse
   Fimenquanto


Fimalgoritmo