Algoritmo "Escolha"
// Função : Lógica de Programação e Algoritmos I
// Autor : Germano Rodrigues da Silva
// Data : 09/07/2024

Var
   voto: literal


Inicio
   Escreval("Digite o seu voto: ")
   Leia(voto)

   Se voto = "20" entao
      Escreval("Você votou no Pernalonga")
   Senao
      Se voto = "30" entao
         Escreval("Você votou no Patolino")
      Senao
         Se voto = "40" entao
            Escreval("Piu-Piu")
         Senao
            Escreval("Voto nulo")
         Fimse
      Fimse
   Fimse



Fimalgoritmo