Algoritmo "Para_Aula_3-G_2"
// Função : Lógica de Programação e Algoritmos I
// Autor : Germano Rodrigues da Silva
// Data atual  : 10/07/2024
Var
   i, incremento, start, end: inteiro


Inicio
//incrementando
   Escreval("Informe o numero inicial")
   Leia(start)
   Escreval("Informe o numero final")
   Leia(end)
   Escreval("Informe o numero incremento ou decremento com '-' na frente")
   Leia(incremento)
   Para i De start Ate end passo incremento Faca
      Escreval(i)
   Fimpara


Fimalgoritmo