Algoritmo "Para_Aula_3-H"
// Função : Lógica de Programação e Algoritmos I
// Autor : Germano Rodrigues da Silva
// Data atual  : 10/07/2024
Var
   i, aleatorioMaximo, aleatorioMinimo, incremento : inteiro


Inicio
   Repita
      Aleatorio 1,100
      Leia(aleatorioMaximo)
      Leia(aleatorioMinimo)
      Aleatorio off
   Ate aleatorioMaximo >= aleatorioMinimo
   Limpatela
   Aleatorio 1,5
             Leia(incremento)
   Aleatorio off
   Limpatela

   Para i De aleatorioMinimo Ate aleatorioMaximo Passo incremento Faca
      Escreval(i)
   Fimpara
Fimalgoritmo