Algoritmo "Trabalhando com Tipos"
// Disciplina   : [Linguagem e Lógica de Programação]
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Germano Rodrigues da Silva
// Data atual  : 07/07/2024
Var
// Seção de Declarações das variáveis 
palavra1, palavra2, palavra3: caracter
numero1, numero2, numero3: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
Escreval("Palavra 1: ")
Leia(palavra1)
Escreval("Palavra 2: ")
Leia(palavra2)
Escreval("Número 1: ")
Leia(numero1)
Escreval("Número 2: ")
Leia(numero2)
palavra3 <- palavra1 + palavra2
numero3 <- numero1+numero2
Escreval(palavra3)
Escreval(numero3)

Fimalgoritmo