Algoritmo "Orientacao_a_objetos-Aula_4-C"
// Disciplina: Lógica de Programação e Algoritmos II
// Autor: Germano Rodrigues da Silva
// Data atual  : 12/07/2024

Tipo
   //Tambem chamados de class em outras linguagens
   livro = registro
      nome : caracter
      isbn : caracter
      qtdPag : inteiro
   fimregistro
Var
   livro1 : livro
   livro2 : livro

Inicio
livro1.nome <- "Sr dos Aneis"
livro2.nome <- "Harry Potter"
Se livro1.nome = livro2.nome entao


Fimalgoritmo